version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/keycloak-lambda-authorizer # directory where steps will run

    docker: # run the steps with Docker
      - image: circleci/node:12.16.1 # ...with this image as the primary container; this is where all `steps` will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory

      - run:
          name: build source
          command: npm i && cd keycloak-cloudfront-dynamodb && npm i
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build example/keycloak-authorizer serverless
          command: cd example/keycloak-authorizer/serverless && npm i
      - run:
          name: lint example/keycloak-authorizer serverless
          command: cd example/keycloak-authorizer/serverless && npm run lint
      - run:
          name: build example/keycloak-authorizer serverless-jwks
          command: cd example/keycloak-authorizer/serverless-jwks && npm i
      - run:
          name: lint example/keycloak-authorizer serverless-jwks
          command: cd example/keycloak-authorizer/serverless-jwks && npm run lint
      - run:
          name: build example/keycloak-authorizer ui
          command: cd example/keycloak-authorizer/ui && npm i
      - run:
          name: lint example/keycloak-authorizer ui
          command: cd example/keycloak-authorizer/ui && npm run lint

      - run:
          name: build example/keycloak-cloudfront cloudfront
          command: cd example/keycloak-cloudfront && npm i
      - run:
          name: lint example/keycloak-cloudfront cloudfront
          command: cd example/keycloak-cloudfront && npm run lint